Try using web3.eth.get_logs instead of ContractEvent.getLogs()
  * ContractEvent.getLogs() requires the contract to be instated but
    in this method, we don't know the contract address.
  * Previous commit threw error:
    TypeError: This method can be only called on an instated contract with an address